### ISSUE TITLE
Error: invalid bytecode (argument="bytecode", value="0x60c0604052...")

### ISSUE THREAD

**Issue by amintalebi** [Uniswap/hardhat-v3-deploy#5]
Hi 
I'm getting following error when I'm trying deploy the contracts.

```
 at Logger.makeError (/Users/amin/Development/uniswapv3-develop/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/amin/Development/uniswapv3-develop/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Logger.throwArgumentError (/Users/amin/Development/uniswapv3-develop/node_modules/@ethersproject/logger/src.ts/index.ts:241:21)
    at new ContractFactory (/Users/amin/Development/uniswapv3-develop/node_modules/@ethersproject/contracts/src.ts/index.ts:1162:20)
    at UniswapV3Deployer.deployContract (/Users/amin/Development/uniswapv3-develop/node_modules/uniswap-v3-deploy-plugin/src/deployer/UniswapV3Deployer.ts:139:21)
    at UniswapV3Deployer.deployPositionDescriptor (/Users/amin/Development/uniswapv3-develop/node_modules/uniswap-v3-deploy-plugin/src/deployer/UniswapV3Deployer.ts:112:24)
    at Function.deploy (/Users/amin/Development/uniswapv3-develop/node_modules/uniswap-v3-deploy-plugin/src/deployer/UniswapV3Deployer.ts:27:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9) {
  reason: 'invalid bytecode',
  code: 'INVALID_ARGUMENT',
  argument: 'bytecode',
  ```
Thanks

**Comment by elhaix** [comment]
I'm experiencing the exact same issue.   Initially I was using Node v17.2.0 which rendered the following error:

```
C:\DEV\uniswap-example>npx hardhat deploy-uniswap
An unexpected error occurred:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (C:\DEV\uniswap-example\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:249:21)
    at HDKey.set (C:\DEV\uniswap-example\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (C:\DEV\uniswap-example\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:194:20)
    at deriveKeyFromMnemonicAndPath (C:\DEV\uniswap-example\node_modules\hardhat\src\internal\util\keys-derivation.ts:21:27)
    at derivePrivateKeys (C:\DEV\uniswap-example\node_modules\hardhat\src\internal\core\providers\util.ts:29:52)
    at normalizeHardhatNetworkAccountsConfig (C:\DEV\uniswap-example\node_modules\hardhat\src\internal\core\providers\util.ts:56:10)
    at createProvider (C:\DEV\uniswap-example\node_modules\hardhat\src\internal\core\providers\construction.ts:78:59)
    at C:\DEV\uniswap-example\node_modules\hardhat\src\internal\core\runtime-environment.ts:80:28 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

I downgraded to node v16.13.1 and that's when I got the same error:

![image](https://user-images.githubusercontent.com/296048/145905518-809cc92f-df05-4baa-af08-14ea6094045a.png)

And adds the following info:

```
...164736f6c6343000706000a", code=INVALID_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (C:\DEV\uniswap-example\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (C:\DEV\uniswap-example\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at Logger.throwArgumentError (C:\DEV\uniswap-example\node_modules\@ethersproject\logger\src.ts\index.ts:241:21)
    at new ContractFactory (C:\DEV\uniswap-example\node_modules\@ethersproject\contracts\src.ts\index.ts:1162:20)
    at UniswapV3Deployer.deployContract (C:\DEV\uniswap-example\node_modules\uniswap-v3-deploy-plugin\src\deployer\UniswapV3Deployer.ts:139:21)
    at UniswapV3Deployer.deployPositionDescriptor (C:\DEV\uniswap-example\node_modules\uniswap-v3-deploy-plugin\src\deployer\UniswapV3Deployer.ts:112:24)
    at Function.deploy (C:\DEV\uniswap-example\node_modules\uniswap-v3-deploy-plugin\src\deployer\UniswapV3Deployer.ts:27:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9) {
  reason: 'invalid bytecode',
  code: 'INVALID_ARGUMENT',
  argument: 'bytecode',
  value: '0x60c060405234801561001057600080fd5b5060405161158038038061158083398101604081905261002f9161004a565b60609190911b6001600160601b0319...
```

I recompiled, same thing.

npx hardhat:  "deploy-uniswap" appears in the tasks.

**Comment by Mubashir-ali-baig** [comment]
I'm also facing the exact same problem, can anybody please guide as my unit tests are fully depended on this one.

**Comment by 5hanth** [comment]
+1

**Comment by nimcon** [comment]
+1

**Comment by pengjichen** [comment]
There's a push request for modify constructor function to add a parameter: 
https://github.com/Uniswap/v3-periphery/commit/de4e437ae97ba21d71a856167968ea05a05853fe#diff-b3b935014f582f4d5c57708462aded987557ad530fecb876901a395eb84bc2f4. 
The code that deploys the contract NonfungibleTokenPositionDescriptor.sol needs to be updated.

**Comment by gravity-link** [comment]
> There's a push request for modify constructor function to add a parameter: [Uniswap/v3-periphery@de4e437#diff-b3b935014f582f4d5c57708462aded987557ad530fecb876901a395eb84bc2f4](https://github.com/Uniswap/v3-periphery/commit/de4e437ae97ba21d71a856167968ea05a05853fe#diff-b3b935014f582f4d5c57708462aded987557ad530fecb876901a395eb84bc2f4). The code that deploys the contract NonfungibleTokenPositionDescriptor.sol needs to be updated.

still 'invalid bytecode', seems not work.

**Comment by gillestasse** [comment]
Same issue.
node v16.13.1
uniswap-v3-deploy-plugin 0.1.0
hardhat 2.8.2

**Comment by bradj00** [comment]
> Had the same issue.
> 
> My dependencies looked like : "dependencies": { "@openzeppelin/contracts": "^4.4.2", "@openzeppelin/contracts-upgradeable": "^4.4.2", "@uniswap/v3-periphery": "^1.4.0", "bignumber.js": "^9.0.2", "dotenv": "^11.0.0", "uniswap-v3-deploy-plugin": "^0.1.0" }
> 
> I _downgraded_ and **installed** to :
> 
> "dependencies": { "@openzeppelin/contracts": "^4.4.2", "@openzeppelin/contracts-upgradeable": "^4.4.2", **"@uniswap/v3-core": "^1.0.0",** _"@uniswap/v3-periphery": "^1.0.1",_ "bignumber.js": "^9.0.2", "dotenv": "^11.0.0", **"uniswap-v3-deploy-plugin": "^0.1.0"** }
> 
> And now it works

What did you downgrade, your node version? I have the same problem and modified my `package.json` to your suggested versions but I still get the same `Error: invalid bytecode` complaint.

**Comment by zed-wong** [comment]
![image](https://user-images.githubusercontent.com/36271125/168412148-958021fb-244e-4dfe-a91a-34e81a22cc2a.png)

Had the same issue.

**Comment by hotdogchain** [comment]
+1

**Comment by beihaili** [comment]
same

**Comment by cryptoshan12** [comment]
same here

**Comment by FracaShaw-Alk** [comment]
same here

**Comment by baotao2006** [comment]
change two points:
$ vi src/deployer/UniswapV3Deployer.ts
  
```
async deployPositionDescriptor(
    nftDescriptorLibraryAddress: string,
    weth9Address: string
  ) {
    const linkedBytecode = linkLibraries(
      {
        bytecode: artifacts.NonfungibleTokenPositionDescriptor.bytecode,
        linkReferences: {
          "NFTDescriptor.sol": {
            NFTDescriptor: [
              {
                length: 20,
                start: 1681,  // old value is 1261
              },
            ],
          },
        },
      },
      {
        NFTDescriptor: nftDescriptorLibraryAddress,
      }
    );

    return (await this.deployContract(
      artifacts.NonfungibleTokenPositionDescriptor.abi,
      linkedBytecode,
      // 'ETH' as a bytes32 string
      [weth9Address, '0x4554480000000000000000000000000000000000000000000000000000000000'],
      this.deployer
    )) as Contract;
  }
```

**Comment by vladimir-trifonov** [comment]
> 
Try with:
```
"dependencies": {
  "@openzeppelin/contracts": "4.4.2",
  "@openzeppelin/contracts-upgradeable": "4.4.2",
  "@uniswap/v3-core": "1.0.0",
  "@uniswap/v3-periphery": "1.0.1",
  "bignumber.js": "9.0.2",
  "dotenv": "11.0.0",
  "uniswap-v3-deploy-plugin": "0.1.0"
}
```

**Comment by StrawberryChocolateFudge** [comment]
> change two points: $ vi src/deployer/UniswapV3Deployer.ts
> 
> ```
> async deployPositionDescriptor(
>     nftDescriptorLibraryAddress: string,
>     weth9Address: string
>   ) {
>     const linkedBytecode = linkLibraries(
>       {
>         bytecode: artifacts.NonfungibleTokenPositionDescriptor.bytecode,
>         linkReferences: {
>           "NFTDescriptor.sol": {
>             NFTDescriptor: [
>               {
>                 length: 20,
>                 start: 1681,  // old value is 1261
>               },
>             ],
>           },
>         },
>       },
>       {
>         NFTDescriptor: nftDescriptorLibraryAddress,
>       }
>     );
> 
>     return (await this.deployContract(
>       artifacts.NonfungibleTokenPositionDescriptor.abi,
>       linkedBytecode,
>       // 'ETH' as a bytes32 string
>       [weth9Address, '0x4554480000000000000000000000000000000000000000000000000000000000'],
>       this.deployer
>     )) as Contract;
>   }
> ```

This was the correct solution! Thank you so much!

**Comment by vspaxo** [comment]
> change two points: $ vi src/deployer/UniswapV3Deployer.ts
> 
> ```
> async deployPositionDescriptor(
>     nftDescriptorLibraryAddress: string,
>     weth9Address: string
>   ) {
>     const linkedBytecode = linkLibraries(
>       {
>         bytecode: artifacts.NonfungibleTokenPositionDescriptor.bytecode,
>         linkReferences: {
>           "NFTDescriptor.sol": {
>             NFTDescriptor: [
>               {
>                 length: 20,
>                 start: 1681,  // old value is 1261
>               },
>             ],
>           },
>         },
>       },
>       {
>         NFTDescriptor: nftDescriptorLibraryAddress,
>       }
>     );
> 
>     return (await this.deployContract(
>       artifacts.NonfungibleTokenPositionDescriptor.abi,
>       linkedBytecode,
>       // 'ETH' as a bytes32 string
>       [weth9Address, '0x4554480000000000000000000000000000000000000000000000000000000000'],
>       this.deployer
>     )) as Contract;
>   }
> ```

works

**Comment by SabeloMkhwanzi** [comment]
```
      "dependencies": {
        "@openzeppelin/contracts": "4.4.2",
        "@openzeppelin/contracts-upgradeable": "4.4.2",
        "@uniswap/v3-core": "1.0.0",
        "@uniswap/v3-periphery": "1.0.1",
        "bignumber.js": "9.0.2",
        "dotenv": "11.0.0",
        "uniswap-v3-deploy-plugin": "0.1.0"
      },
```
This work for me after -  I pasted this dependencies inside  node_modules/@uniswap/hardhat-v3-deploy/package.json

**Comment by andykimisgreat** [comment]
> ```
>       "dependencies": {
>         "@openzeppelin/contracts": "4.4.2",
>         "@openzeppelin/contracts-upgradeable": "4.4.2",
>         "@uniswap/v3-core": "1.0.0",
>         "@uniswap/v3-periphery": "1.0.1",
>         "bignumber.js": "9.0.2",
>         "dotenv": "11.0.0",
>         "uniswap-v3-deploy-plugin": "0.1.0"
>       },
> ```
> 
> This work for me after - I pasted this dependencies inside node_modules/@uniswap/hardhat-v3-deploy/package.json

Worked.

**Comment by ibrahim1023** [comment]
Is anyone still facing the issue despite the above suggestions? I did everything suggested above but no luck!
